### PR TITLE
Update dotnet docker images to .NET 7 and enable dynamic PGO

### PR DESCRIPTION
**Pull request by JamesNK**
cc @jtattermusch

### CODE REVIEW

**Comment by JamesNK** [comment]
I don't have benchmarks set up locally, and I haven't tested this. 

I think this might allow OSS benchmarks to be re-enabled. That means https://github.com/grpc/grpc/pull/30787 can be reverted.

**Comment by wanlin31** [comment]
I have verified the images by running regular and pre-built test on benchmark-dev1 cluster.  LGTM.

**Review by wanlin31 — APPROVED** [review]

**Comment by JamesNK** [comment]
Will you revert https://github.com/grpc/grpc/pull/30787 or should I create a PR for it?

**Comment by wanlin31** [comment]
> [grpc/grpc#30787](https://github.com/grpc/grpc/pull/30787)

Let me revert https://github.com/grpc/grpc/pull/30787. Thank you for fixing the images!

**Pull request merged**
