### PR TITLE
Feature/node image

### PR DESCRIPTION
**Pull request by wanlin31**
I am still working on images to support Node.js tests. The build and runtime image works fine, but when I run a LoadTest, the driver logs shows that it stuck in between. Need further investigation.

### CODE REVIEW

**Comment by wanlin31** [comment]
The node.js support is added, however, the example node LoadTest could not be finished succeeded due to issues related to the test itself.

**Review by paulosjca — APPROVED** [review]

**Review by codeblooded — COMMENTED** [review]
This LGTM, but should we merge if we do not have a way to test it is working properly? How do we know the port server issue does not live with node?

**Comment by wanlin31** [comment]
Verified with deployed controller on benchmarks-dev1, reach the same status as when we run a controller agains the cluster.

**Comment by wanlin31** [comment]
@codeblooded Anything wired about the checks? I failed a lot of times at go built, but I could not replicate the error locally? Any idea?

**Review by codeblooded — APPROVED** [review]

**Pull request merged**
