### PR TITLE
Update example tests.

### PR DESCRIPTION
**Pull request by paulosjca**
Tests are updated following https://github.com/grpc/grpc/pull/33968.

### CODE REVIEW

**Review by drfloob — APPROVED** [review]
Are these auto-generated, or was this done manually?

**Comment by murgatroid99** [comment]
If it matters functionally what the names say, then the new `node_purejs_to_node` strings should probably say `node_purejs_to_node_purejs`. And if it doesn't matter functionally, then it's probably not worth changing the names at all, and we can just say that we now use `node` to refer to the new pure JS implementation instead of the old wrapper implementation.

**Comment by paulosjca** [comment]
They are generated by running the script updated by https://github.com/grpc/grpc/pull/33968.

https://github.com/grpc/grpc/blob/master/tools/run_tests/performance/README.md#generating-load-test-examples

**Comment by murgatroid99** [comment]
So maybe that script should say `node` instead of `node_purejs`

**Comment by paulosjca** [comment]
Currently it does matter functionally. This was likely a hack back in the day, to generate scenarios with two different configurations they were named as two different languages, `node` and `node_purejs`. This only affects the scenario naming and configuration, not the actual worker. If you want to drop the old `node` implementation completely and rename things so there is only `node`, we can do that as a follow-up step. The key to how this works is here:

https://github.com/grpc/grpc/blob/e0b51886be667c191a93885c98102872aa2b922f/tools/run_tests/performance/scenario_config.py#L1796

**Comment by paulosjca** [comment]
Let's merge the examples since they are only examples and they show how the code is actually working now (for instance, in the experimental ci: https://github.com/grpc/grpc/pull/33963). We can update them again if that changes.

**Comment by murgatroid99** [comment]
I think those scenarios might actually have run the pure JS client against the wrapper server, so the names were correct. I think they predate the existence of the pure JS server implementation.

But I wouldn't expect that we're using `scenario_config.py` anymore anyway, because it runs worker commands that don't correspond to the docker images we use in this repository.

**Comment by paulosjca** [comment]
> So maybe that script should say `node` instead of `node_purejs`

If it does, then the scenarios will be generated with the old implementation. Feel free to deprecate the old implementation and make the change throughout.

**Comment by murgatroid99** [comment]
The updated worker docker image only runs the pure JS implementation. It can't be configured to run the old implementation. So the scenario can describe itself as using the old implementation, but it won't actually run the old implementation.

**Comment by paulosjca** [comment]
> The updated worker docker image only runs the pure JS implementation. It can't be configured to run the old implementation. So the scenario can describe itself as using the old implementation, but it won't actually run the old implementation.

This is a good reason to clean up `scenario_config.py`. We do generate the scenarios based on that. In any case, the test will be the same.

**Comment by murgatroid99** [comment]
My perspective here is that there's no reason to keep the `purejs` string in the long run, so adding it to various places now just makes more work when we remove it later.

**Comment by paulosjca** [comment]
Let's deprecate `node_purejs` instead.

**Comment by paulosjca** [comment]
Superseded by https://github.com/grpc/test-infra/pull/378.

**Pull request closed without merging**
