### PR TITLE
Add ginkgo BDD testing framework

### PR DESCRIPTION
**Pull request by codeblooded**
We are looking to develop a custom controller to orchestrate the tests. Google Cloud Platform recommends that projects use a framework like kubebuilder, see [Best practices for building Kubernetes Operators and stateful apps](https://cloud.google.com/blog/products/containers-kubernetes/best-practices-for-building-kubernetes-operators-and-stateful-apps). Development with this framework is partially tracked in #5.

The kubebuilder project encourages the use of [Ginkgo](http://onsi.github.io/ginkgo/), a BDD testing framework for Go. Their generators and recommended examples use it. See kubernetes-sigs/kubebuilder#822. Ginkgo has a companion assertion/matcher library, [Gomega](http://onsi.github.io/gomega/).

This change adds Ginkgo and Gomega to the project as dependencies. Both are officially MIT Licensed with additional third party dependencies. See [Ginkgo dependencies](https://github.com/onsi/ginkgo/blob/master/go.sum) and [Gomega dependencies](https://github.com/onsi/gomega/blob/master/go.sum) for a full listing.

This is a separate PR, so I can begin to write tests in Ginkgo's style before we merge the controller.

### CODE REVIEW

**Comment by codeblooded** [comment]
I realized that an old version of ginkgo was installed on my machine causing it to select an old version. I've updated to the latest version to match kubebuilder PR #5.

**Comment by jtattermusch** [comment]
I don't know enough of Ginkgo to be able to evaluate if it's a good choice or not - I'll leave it up to you to do the research and decide if that's what we want to use.

**Comment by codeblooded** [comment]
Due to  kubernetes-sigs/kubebuilder#822, I think it's a good choice. It does not match the xunit style that @paulosjca and I are used to. However, the documentation for testing kubebuilder is fairly limited.

The main examples recommended by the kubebuilder team use ginkgo. The kubebuilder tool itself creates ginkgo test suites. The kubebuilder team seems to embrace and recommend it, since it does provide better setup and tear-down facilities than the standard library's testing package.

For me, it's a question about whether these dependencies are okay with you guys. Since we're using kubebuilder, I think it makes sense.

**Comment by jtattermusch** [comment]
I'm ok with using it if @paulosjca  is ok.

**Pull request merged**
